#!/bin/bash
# This script updates the nightly release on GitHub for thicc
# Requires: GitHub CLI (gh) authenticated
# Must be run from inside the thicc git repository
#
# Usage: ./nightly-release.sh

set -e

# Ensure we're in the repo root
cd "$(git rev-parse --show-toplevel)"

COMMIT_ID=$(git rev-parse --short HEAD)
VERSION="nightly"

echo "Building nightly release for commit $COMMIT_ID..."

echo "Cross compiling binaries..."
./tools/cross-compile.sh "$VERSION"

# Check if nightly release exists
if gh release view nightly >/dev/null 2>&1; then
    echo "Updating existing nightly release..."

    # Delete old assets
    echo "Removing old assets..."
    gh release view nightly --json assets -q '.assets[].name' | while read -r asset; do
        gh release delete-asset nightly "$asset" --yes 2>/dev/null || true
    done

    # Upload new assets
    echo "Uploading new assets..."
    gh release upload nightly binaries/thicc-"$VERSION"-* --clobber

    # Update release notes
    gh release edit nightly \
        --title "nightly" \
        --notes "Nightly build

Autogenerated nightly build of thicc.
Assets uploaded on $(date) for commit $COMMIT_ID.

**Note:** Please disregard the creation date of this GitHub release - only the asset upload date matters."
else
    echo "Creating new nightly release..."
    gh release create nightly \
        --title "nightly" \
        --notes "Nightly build

Autogenerated nightly build of thicc.
Assets uploaded on $(date) for commit $COMMIT_ID." \
        --prerelease \
        binaries/thicc-"$VERSION"-*
fi

echo "Cleaning up..."
rm -rf binaries

echo ""
echo "Nightly release updated successfully!"
echo "View at: https://github.com/elleryfamilia/thicc/releases/tag/nightly"
